name: PlaidCow
favicon: null
layout_spectrum: 0.5161996812094003
typography_spectrum: 0.48159971949644387
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#9D2D3C'
    - '#DDE4DD'
    - '#BCAB47'
    - '#6B574B'
    - '#160600'
  brandStrength: 0.38236547680571675
  lightness: 0.9023758007679135
  saturation: 0.19158950611017644
  rhythmicContrast: 0.1638951231725514
purpose: []
